package com.carddemo.transaction.service;

import com.carddemo.transaction.dto.AddTransactionRequest;
import com.carddemo.transaction.dto.AddTransactionResponse;
import com.carddemo.transaction.dto.TransactionResponse;
import com.carddemo.transaction.entity.CardCrossReference;
import com.carddemo.transaction.entity.Transaction;
import com.carddemo.transaction.exception.AccountNotFoundException;
import com.carddemo.transaction.exception.CardNotFoundException;
import com.carddemo.transaction.exception.TransactionNotFoundException;
import com.carddemo.transaction.repository.CardCrossReferenceRepository;
import com.carddemo.transaction.repository.TransactionRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of the TransactionService.
 *
 * This class contains the migrated business logic from COTRN02C.cbl,
 * specifically the PROCEDURE DIVISION paragraphs:
 *
 *   - VALIDATE-INPUT-KEY-FIELDS  -> resolveCardNumber()
 *   - ADD-TRANSACTION            -> addTransaction()
 *   - COPY-LAST-TRAN-DATA        -> getLatestTransaction()
 *   - READ-CCXREF-FILE           -> lookupByCardNumber()
 *   - READ-CXACAIX-FILE          -> lookupByAccountId()
 *   - WRITE-TRANSACT-FILE        -> transactionRepository.save()
 *
 * The COBOL auto-increment pattern (STARTBR HIGH-VALUES, READPREV, +1)
 * is replaced by a database sequence via JPA @GeneratedValue.
 */
@Service
public class TransactionServiceImpl implements TransactionService {

    private final TransactionRepository transactionRepository;
    private final CardCrossReferenceRepository cardCrossReferenceRepository;

    public TransactionServiceImpl(
            TransactionRepository transactionRepository,
            CardCrossReferenceRepository cardCrossReferenceRepository) {
        this.transactionRepository = transactionRepository;
        this.cardCrossReferenceRepository = cardCrossReferenceRepository;
    }

    @Override
    @Transactional
    public AddTransactionResponse addTransaction(AddTransactionRequest request) {
        // Step 1: Resolve card number via cross-reference lookup
        // Replaces VALIDATE-INPUT-KEY-FIELDS
        String cardNumber = resolveCardNumber(request);

        // Step 2: Build the transaction entity
        // Replaces ADD-TRANSACTION paragraph (lines 442-466 in COTRN02C.cbl)
        Transaction transaction = new Transaction();
        transaction.setTypeCode(request.getTypeCode());
        transaction.setCategoryCode(request.getCategoryCode());
        transaction.setSource(request.getSource());
        transaction.setDescription(request.getDescription());
        transaction.setAmount(request.getAmount());
        transaction.setCardNumber(cardNumber);
        transaction.setMerchantId(request.getMerchantId());
        transaction.setMerchantName(request.getMerchantName());
        transaction.setMerchantCity(request.getMerchantCity());
        transaction.setMerchantZip(request.getMerchantZip());
        transaction.setOriginatedTs(request.getOriginatedDate().atStartOfDay());
        transaction.setProcessedTs(request.getProcessedDate().atStartOfDay());

        // Step 3: Save (replaces WRITE-TRANSACT-FILE)
        // ID is auto-generated by the database sequence, replacing
        // the COBOL pattern of STARTBR HIGH-VALUES + READPREV + ADD 1
        Transaction saved = transactionRepository.save(transaction);

        // Step 4: Return success response
        // Replaces: STRING 'Transaction added successfully. '
        //           ' Your Tran ID is ' TRAN-ID '.' INTO WS-MESSAGE
        return new AddTransactionResponse(
                saved.getTransactionId(),
                "Transaction added successfully. Your Tran ID is "
                        + saved.getTransactionId() + "."
        );
    }

    @Override
    @Transactional(readOnly = true)
    public TransactionResponse getTransaction(Long transactionId) {
        Transaction transaction = transactionRepository.findById(transactionId)
                .orElseThrow(() -> new TransactionNotFoundException(transactionId));
        return mapToResponse(transaction);
    }

    @Override
    @Transactional(readOnly = true)
    public TransactionResponse getLatestTransaction() {
        // Replaces COPY-LAST-TRAN-DATA paragraph:
        //   MOVE HIGH-VALUES TO TRAN-ID
        //   PERFORM STARTBR-TRANSACT-FILE
        //   PERFORM READPREV-TRANSACT-FILE
        //   PERFORM ENDBR-TRANSACT-FILE
        Transaction transaction = transactionRepository.findFirstByOrderByTransactionIdDesc()
                .orElseThrow(() -> new TransactionNotFoundException(
                        "No transactions found in the system"));
        return mapToResponse(transaction);
    }

    /**
     * Resolve the card number from the request.
     *
     * If cardNumber is provided, validate it exists in the cross-reference.
     * If only accountId is provided, look up the card number via the
     * alternate index (CXACAIX).
     *
     * Replaces VALIDATE-INPUT-KEY-FIELDS paragraph (lines 193-230).
     */
    private String resolveCardNumber(AddTransactionRequest request) {
        if (request.getCardNumber() != null && !request.getCardNumber().isBlank()) {
            // Path: Card number provided -> lookup in CCXREF
            // Replaces: READ DATASET(WS-CCXREF-FILE) RIDFLD(XREF-CARD-NUM)
            CardCrossReference xref = cardCrossReferenceRepository
                    .findByCardNumber(request.getCardNumber())
                    .orElseThrow(() -> new CardNotFoundException(request.getCardNumber()));
            return xref.getCardNumber();
        } else if (request.getAccountId() != null) {
            // Path: Account ID provided -> lookup card via CXACAIX alternate index
            // Replaces: READ DATASET(WS-CXACAIX-FILE) RIDFLD(XREF-ACCT-ID)
            CardCrossReference xref = cardCrossReferenceRepository
                    .findFirstByAccountId(request.getAccountId())
                    .orElseThrow(() -> new AccountNotFoundException(request.getAccountId()));
            return xref.getCardNumber();
        }

        // Should not reach here due to @AccountOrCard validation
        throw new IllegalArgumentException("Account ID or Card Number must be provided");
    }

    /**
     * Map a Transaction entity to a TransactionResponse DTO.
     * Replaces the COBOL MOVE statements that populate screen output fields.
     */
    private TransactionResponse mapToResponse(Transaction transaction) {
        TransactionResponse response = new TransactionResponse();
        response.setTransactionId(transaction.getTransactionId());
        response.setTypeCode(transaction.getTypeCode());
        response.setCategoryCode(transaction.getCategoryCode());
        response.setSource(transaction.getSource());
        response.setDescription(transaction.getDescription());
        response.setAmount(transaction.getAmount());
        response.setMerchantId(transaction.getMerchantId());
        response.setMerchantName(transaction.getMerchantName());
        response.setMerchantCity(transaction.getMerchantCity());
        response.setMerchantZip(transaction.getMerchantZip());
        response.setCardNumber(transaction.getCardNumber());
        response.setOriginatedTs(transaction.getOriginatedTs());
        response.setProcessedTs(transaction.getProcessedTs());
        return response;
    }
}
