server.port=8088
spring.application.name=report-service

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:reportdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# H2 Console (for development)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
