-- Daily transactions staging table for batch processing
-- Same structure as transactions but with auto-generated ID
CREATE TABLE daily_transactions (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_id          VARCHAR(16),
    transaction_type        VARCHAR(2),
    transaction_category    INTEGER,
    transaction_source      VARCHAR(10),
    transaction_description VARCHAR(100),
    transaction_amount      DECIMAL(11,2),
    merchant_id             VARCHAR(9),
    merchant_name           VARCHAR(50),
    merchant_city           VARCHAR(50),
    merchant_zip            VARCHAR(10),
    card_number             VARCHAR(16),
    origin_timestamp        VARCHAR(26),
    processing_timestamp    VARCHAR(26),
    CONSTRAINT pk_daily_transactions PRIMARY KEY (id)
);
