spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none

batch:
  reports:
    input-dir: ./data/input
    output-dir: ./data/output
