// <auto-generated />
using System;
using CardDemo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CardDemo.Infrastructure.Migrations
{
    [DbContext(typeof(CardDemoDbContext))]
    partial class CardDemoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardDemo.Core.Entities.Account", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("AddressZip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("CashCreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CurrentCycleCredit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CurrentCycleDebit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ExpirationDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OpenDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ReissueDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("AccountId");

                    b.ToTable("accounts", (string)null);

                    b.HasData(
                        new
                        {
                            AccountId = 80000000001L,
                            AccountStatus = "Y",
                            AddressZip = "10001",
                            CashCreditLimit = 1500.00m,
                            CreditLimit = 5000.00m,
                            CurrentBalance = 1500.50m,
                            CurrentCycleCredit = 200.00m,
                            CurrentCycleDebit = 350.75m,
                            ExpirationDate = "2027-01-15",
                            GroupId = "GRP00001",
                            OpenDate = "2020-01-15",
                            ReissueDate = "2025-01-15"
                        },
                        new
                        {
                            AccountId = 80000000002L,
                            AccountStatus = "Y",
                            AddressZip = "90210",
                            CashCreditLimit = 3000.00m,
                            CreditLimit = 10000.00m,
                            CurrentBalance = 3200.00m,
                            CurrentCycleCredit = 500.00m,
                            CurrentCycleDebit = 1200.50m,
                            ExpirationDate = "2026-06-20",
                            GroupId = "GRP00002",
                            OpenDate = "2019-06-20",
                            ReissueDate = "2024-06-20"
                        },
                        new
                        {
                            AccountId = 80000000003L,
                            AccountStatus = "Y",
                            AddressZip = "75001",
                            CashCreditLimit = 1000.00m,
                            CreditLimit = 3000.00m,
                            CurrentBalance = 750.25m,
                            CurrentCycleCredit = 100.00m,
                            CurrentCycleDebit = 200.00m,
                            ExpirationDate = "2028-03-10",
                            GroupId = "GRP00001",
                            OpenDate = "2021-03-10",
                            ReissueDate = "2026-03-10"
                        });
                });

            modelBuilder.Entity("CardDemo.Core.Entities.CardCrossReference", b =>
                {
                    b.Property<string>("CardNumber")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.HasKey("CardNumber");

                    b.HasIndex("AccountId");

                    b.HasIndex("CustomerId");

                    b.ToTable("card_xref", (string)null);

                    b.HasData(
                        new
                        {
                            CardNumber = "4111111111111111",
                            AccountId = 80000000001L,
                            CustomerId = 100000001L
                        },
                        new
                        {
                            CardNumber = "4222222222222222",
                            AccountId = 80000000002L,
                            CustomerId = 100000002L
                        },
                        new
                        {
                            CardNumber = "4333333333333333",
                            AccountId = 80000000003L,
                            CustomerId = 100000003L
                        });
                });

            modelBuilder.Entity("CardDemo.Core.Entities.CardData", b =>
                {
                    b.Property<string>("CardNumber")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("CardStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int>("CvvCode")
                        .HasColumnType("integer");

                    b.Property<string>("EmbossedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ExpirationDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("CardNumber");

                    b.HasIndex("AccountId");

                    b.ToTable("card_data", (string)null);

                    b.HasData(
                        new
                        {
                            CardNumber = "4111111111111111",
                            AccountId = 80000000001L,
                            CardStatus = "Y",
                            CvvCode = 123,
                            EmbossedName = "JOHN M SMITH",
                            ExpirationDate = "2027-01-15"
                        },
                        new
                        {
                            CardNumber = "4222222222222222",
                            AccountId = 80000000002L,
                            CardStatus = "Y",
                            CvvCode = 456,
                            EmbossedName = "JANE E DOE",
                            ExpirationDate = "2026-06-20"
                        },
                        new
                        {
                            CardNumber = "4333333333333333",
                            AccountId = 80000000003L,
                            CardStatus = "Y",
                            CvvCode = 789,
                            EmbossedName = "ROBERT J JOHNSON",
                            ExpirationDate = "2028-03-10"
                        });
                });

            modelBuilder.Entity("CardDemo.Core.Entities.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AddressLine3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("EftAccountId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("FicoScore")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("GovtIssuedId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("PhoneNumber1")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("PhoneNumber2")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("PrimaryCardHolderIndicator")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("Ssn")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("CustomerId");

                    b.ToTable("customers", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerId = 100000001L,
                            AddressLine1 = "123 Main Street",
                            AddressLine2 = "Apt 4B",
                            AddressLine3 = "",
                            CountryCode = "USA",
                            DateOfBirth = "1985-03-15",
                            EftAccountId = "EFT0000001",
                            FicoScore = 750,
                            FirstName = "John",
                            GovtIssuedId = "NY-DL-12345678",
                            LastName = "Smith",
                            MiddleName = "Michael",
                            PhoneNumber1 = "212-555-0101",
                            PhoneNumber2 = "212-555-0102",
                            PrimaryCardHolderIndicator = "Y",
                            Ssn = "123456789",
                            State = "NY",
                            ZipCode = "10001"
                        },
                        new
                        {
                            CustomerId = 100000002L,
                            AddressLine1 = "456 Oak Avenue",
                            AddressLine2 = "",
                            AddressLine3 = "",
                            CountryCode = "USA",
                            DateOfBirth = "1990-07-22",
                            EftAccountId = "EFT0000002",
                            FicoScore = 680,
                            FirstName = "Jane",
                            GovtIssuedId = "CA-DL-87654321",
                            LastName = "Doe",
                            MiddleName = "Elizabeth",
                            PhoneNumber1 = "310-555-0201",
                            PhoneNumber2 = "",
                            PrimaryCardHolderIndicator = "Y",
                            Ssn = "987654321",
                            State = "CA",
                            ZipCode = "90210"
                        },
                        new
                        {
                            CustomerId = 100000003L,
                            AddressLine1 = "789 Pine Road",
                            AddressLine2 = "Suite 100",
                            AddressLine3 = "",
                            CountryCode = "USA",
                            DateOfBirth = "1978-11-08",
                            EftAccountId = "EFT0000003",
                            FicoScore = 720,
                            FirstName = "Robert",
                            GovtIssuedId = "TX-DL-45678912",
                            LastName = "Johnson",
                            MiddleName = "James",
                            PhoneNumber1 = "214-555-0301",
                            PhoneNumber2 = "214-555-0302",
                            PrimaryCardHolderIndicator = "Y",
                            Ssn = "456789123",
                            State = "TX",
                            ZipCode = "75001"
                        });
                });

            modelBuilder.Entity("CardDemo.Core.Entities.DailyTransaction", b =>
                {
                    b.Property<long>("DailyTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DailyTransactionId"));

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("MerchantCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MerchantZip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("OriginTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ProcessingTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TransactionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TransactionCategory")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TransactionSource")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("DailyTransactionId");

                    b.HasIndex("CardNumber");

                    b.ToTable("daily_transactions", (string)null);
                });

            modelBuilder.Entity("CardDemo.Core.Entities.DailyTransactionReject", b =>
                {
                    b.Property<long>("DailyTransactionRejectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DailyTransactionRejectId"));

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("MerchantCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MerchantZip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("OriginTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ProcessingTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RejectReasonCode")
                        .HasColumnType("integer");

                    b.Property<string>("RejectReasonDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<decimal>("TransactionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TransactionCategory")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TransactionSource")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("DailyTransactionRejectId");

                    b.HasIndex("CardNumber");

                    b.ToTable("daily_transaction_rejects", (string)null);
                });

            modelBuilder.Entity("CardDemo.Core.Entities.Transaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("MerchantCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MerchantZip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("OriginTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ProcessingTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TransactionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TransactionCategory")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TransactionSource")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("TransactionId");

                    b.HasIndex("CardNumber");

                    b.ToTable("transactions", (string)null);

                    b.HasData(
                        new
                        {
                            TransactionId = "TRN0000000000001",
                            CardNumber = "4111111111111111",
                            MerchantCity = "New York",
                            MerchantId = "100000001",
                            MerchantName = "FreshMart Grocery",
                            MerchantZip = "10001",
                            OriginTimestamp = new DateTime(2025, 12, 1, 10, 30, 0, 0, DateTimeKind.Utc),
                            ProcessingTimestamp = new DateTime(2025, 12, 1, 10, 30, 5, 0, DateTimeKind.Utc),
                            TransactionAmount = 125.50m,
                            TransactionCategory = 5411,
                            TransactionDescription = "Grocery Store Purchase",
                            TransactionSource = "ONLINE",
                            TransactionType = "01"
                        },
                        new
                        {
                            TransactionId = "TRN0000000000002",
                            CardNumber = "4222222222222222",
                            MerchantCity = "Los Angeles",
                            MerchantId = "100000002",
                            MerchantName = "Italian Bistro",
                            MerchantZip = "90210",
                            OriginTimestamp = new DateTime(2025, 12, 2, 19, 15, 0, 0, DateTimeKind.Utc),
                            ProcessingTimestamp = new DateTime(2025, 12, 2, 19, 15, 3, 0, DateTimeKind.Utc),
                            TransactionAmount = 85.75m,
                            TransactionCategory = 5812,
                            TransactionDescription = "Restaurant Dinner",
                            TransactionSource = "POS",
                            TransactionType = "01"
                        },
                        new
                        {
                            TransactionId = "TRN0000000000003",
                            CardNumber = "4333333333333333",
                            MerchantCity = "Dallas",
                            MerchantId = "100000003",
                            MerchantName = "First National Bank",
                            MerchantZip = "75001",
                            OriginTimestamp = new DateTime(2025, 12, 3, 14, 0, 0, 0, DateTimeKind.Utc),
                            ProcessingTimestamp = new DateTime(2025, 12, 3, 14, 0, 2, 0, DateTimeKind.Utc),
                            TransactionAmount = 500.00m,
                            TransactionCategory = 6011,
                            TransactionDescription = "Payment Received",
                            TransactionSource = "ATM",
                            TransactionType = "04"
                        });
                });

            modelBuilder.Entity("CardDemo.Core.Entities.TransactionType", b =>
                {
                    b.Property<string>("TypeCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("TypeDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TypeCode");

                    b.ToTable("transaction_types", (string)null);

                    b.HasData(
                        new
                        {
                            TypeCode = "01",
                            TypeDescription = "Purchase"
                        },
                        new
                        {
                            TypeCode = "02",
                            TypeDescription = "Return"
                        },
                        new
                        {
                            TypeCode = "03",
                            TypeDescription = "Cash Advance"
                        },
                        new
                        {
                            TypeCode = "04",
                            TypeDescription = "Payment"
                        },
                        new
                        {
                            TypeCode = "05",
                            TypeDescription = "Balance Transfer"
                        });
                });

            modelBuilder.Entity("CardDemo.Core.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.HasKey("UserId");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "ADMIN001",
                            FirstName = "Admin",
                            LastName = "User",
                            Password = "CHANGEME",
                            UserType = "A"
                        },
                        new
                        {
                            UserId = "USER0001",
                            FirstName = "Regular",
                            LastName = "User",
                            Password = "CHANGEME",
                            UserType = "U"
                        });
                });

            modelBuilder.Entity("CardDemo.Core.Entities.CardCrossReference", b =>
                {
                    b.HasOne("CardDemo.Core.Entities.Account", "Account")
                        .WithMany("CrossReferences")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardDemo.Core.Entities.Customer", "Customer")
                        .WithMany("CrossReferences")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CardDemo.Core.Entities.CardData", b =>
                {
                    b.HasOne("CardDemo.Core.Entities.Account", "Account")
                        .WithMany("Cards")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CardDemo.Core.Entities.Account", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("CrossReferences");
                });

            modelBuilder.Entity("CardDemo.Core.Entities.Customer", b =>
                {
                    b.Navigation("CrossReferences");
                });
#pragma warning restore 612, 618
        }
    }
}
