-- CS-11 batch transaction posting (CBTRN01-03C / POSTTRAN).
--
-- The legacy CBTRN02C writes rejected daily transactions to the DALYREJS sequential file
-- (FD-REJS-RECORD = 350-byte transaction image + 80-byte validation trailer holding the
-- numeric fail reason + description). The Java posting job (postTranJob) persists the same
-- information to this table instead of a flat reject file, so rejects are queryable and the
-- job stays idempotent per run.
--
-- PostgreSQL-compatible DDL (also runs on H2 in PostgreSQL mode for dev/test).

CREATE TABLE posting_transaction_reject (
    reject_id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    run_id               VARCHAR(36),
    dalytran_id          VARCHAR(16),
    tran_card_num        VARCHAR(16),
    tran_type_cd         VARCHAR(2),
    tran_cat_cd          INTEGER,
    tran_amt             NUMERIC(11,2),
    reject_reason_code   INTEGER      NOT NULL,
    reject_reason_desc   VARCHAR(76),
    CONSTRAINT pk_posting_transaction_reject PRIMARY KEY (reject_id)
);

CREATE INDEX ix_posting_reject_run_id ON posting_transaction_reject (run_id);
CREATE INDEX ix_posting_reject_reason ON posting_transaction_reject (reject_reason_code);
