#!/usr/bin/env python3
"""
Parse fixed-width COBOL Customer records (CVCUS01Y.cpy, RECLN 500)
and generate Flyway-compatible SQL INSERT statements.

Field layout:
  CUST-ID                PIC 9(09)   offset 0,   len 9
  CUST-FIRST-NAME        PIC X(25)   offset 9,   len 25
  CUST-MIDDLE-NAME       PIC X(25)   offset 34,  len 25
  CUST-LAST-NAME         PIC X(25)   offset 59,  len 25
  CUST-ADDR-LINE-1       PIC X(50)   offset 84,  len 50
  CUST-ADDR-LINE-2       PIC X(50)   offset 134, len 50
  CUST-ADDR-LINE-3       PIC X(50)   offset 184, len 50
  CUST-ADDR-STATE-CD     PIC X(02)   offset 234, len 2
  CUST-ADDR-COUNTRY-CD   PIC X(03)   offset 236, len 3
  CUST-ADDR-ZIP          PIC X(10)   offset 239, len 10
  CUST-PHONE-NUM-1       PIC X(15)   offset 249, len 15
  CUST-PHONE-NUM-2       PIC X(15)   offset 264, len 15
  CUST-SSN               PIC 9(09)   offset 279, len 9
  CUST-GOVT-ISSUED-ID    PIC X(20)   offset 288, len 20
  CUST-DOB-YYYY-MM-DD    PIC X(10)   offset 308, len 10
  CUST-EFT-ACCOUNT-ID    PIC X(10)   offset 318, len 10
  CUST-PRI-CARD-HOLDER-IND PIC X(01) offset 328, len 1
  CUST-FICO-CREDIT-SCORE PIC 9(03)   offset 329, len 3
  FILLER                 PIC X(168)  offset 332, len 168  (ignored)
"""

import os
import sys


def sql_escape(value: str) -> str:
    """Escape single quotes for SQL by doubling them."""
    return value.replace("'", "''")


def parse_record(line: str) -> dict:
    """Parse a single fixed-width customer record."""
    return {
        "cust_id": int(line[0:9]),
        "first_name": line[9:34].rstrip(),
        "middle_name": line[34:59].rstrip(),
        "last_name": line[59:84].rstrip(),
        "addr_line_1": line[84:134].rstrip(),
        "addr_line_2": line[134:184].rstrip(),
        "addr_line_3": line[184:234].rstrip(),
        "state_code": line[234:236].rstrip(),
        "country_code": line[236:239].rstrip(),
        "zip_code": line[239:249].rstrip(),
        "phone_num_1": line[249:264].rstrip(),
        "phone_num_2": line[264:279].rstrip(),
        "ssn": int(line[279:288]),
        "govt_issued_id": line[288:308].rstrip(),
        "dob": line[308:318].rstrip(),
        "eft_account_id": line[318:328].rstrip(),
        "pri_card_holder_ind": line[328:329].rstrip(),
        "fico_credit_score": int(line[329:332]),
    }


def to_insert(rec: dict) -> str:
    """Generate a SQL INSERT statement for one record."""
    return (
        f"INSERT INTO customers "
        f"(id, first_name, middle_name, last_name, "
        f"address_line1, address_line2, address_line3, "
        f"state_code, country_code, zip_code, "
        f"phone_number1, phone_number2, "
        f"ssn, govt_issued_id, date_of_birth, "
        f"eft_account_id, primary_card_holder_indicator, fico_credit_score) "
        f"VALUES ("
        f"{rec['cust_id']}, "
        f"'{sql_escape(rec['first_name'])}', "
        f"'{sql_escape(rec['middle_name'])}', "
        f"'{sql_escape(rec['last_name'])}', "
        f"'{sql_escape(rec['addr_line_1'])}', "
        f"'{sql_escape(rec['addr_line_2'])}', "
        f"'{sql_escape(rec['addr_line_3'])}', "
        f"'{sql_escape(rec['state_code'])}', "
        f"'{sql_escape(rec['country_code'])}', "
        f"'{sql_escape(rec['zip_code'])}', "
        f"'{sql_escape(rec['phone_num_1'])}', "
        f"'{sql_escape(rec['phone_num_2'])}', "
        f"{rec['ssn']}, "
        f"'{sql_escape(rec['govt_issued_id'])}', "
        f"'{sql_escape(rec['dob'])}', "
        f"'{sql_escape(rec['eft_account_id'])}', "
        f"'{sql_escape(rec['pri_card_holder_ind'])}', "
        f"{rec['fico_credit_score']}"
        f");"
    )


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)
    input_file = os.path.join(repo_root, "app", "data", "ASCII", "custdata.txt")
    output_file = os.path.join(
        repo_root,
        "java-migration",
        "src",
        "main",
        "resources",
        "db",
        "migration",
        "V1.1__seed_customers.sql",
    )

    records = []
    with open(input_file, "r") as f:
        for line in f:
            line = line.rstrip("\n").rstrip("\r")
            if len(line) < 332:
                continue
            records.append(parse_record(line))

    with open(output_file, "w") as f:
        f.write(
            "-- Flyway migration: seed customer data from COBOL custdata.txt\n"
        )
        f.write(
            "-- Generated by scripts/parse_custdata.py\n"
        )
        f.write(
            f"-- Source: app/data/ASCII/custdata.txt ({len(records)} records)\n\n"
        )
        for rec in records:
            f.write(to_insert(rec) + "\n")

    print(f"Generated {len(records)} INSERT statements in {output_file}")


if __name__ == "__main__":
    main()
