#!/usr/bin/env python3
"""
Parse COBOL disclosure group seed data (discgrp.txt) and generate SQL INSERT statements.

Record layout (from CVTRA02Y.cpy, RECLN = 50):
  Offset  0, Length 10: DIS-ACCT-GROUP-ID  PIC X(10)
  Offset 10, Length  2: DIS-TRAN-TYPE-CD   PIC X(02)
  Offset 12, Length  4: DIS-TRAN-CAT-CD    PIC 9(04)
  Offset 16, Length  6: DIS-INT-RATE       PIC S9(04)V99  (zoned decimal with sign overpunch)
  Offset 22, Length 28: FILLER             PIC X(28)      (ignored)

Zoned decimal sign overpunch (last digit of DIS-INT-RATE):
  Positive: { = 0, A = 1, B = 2, C = 3, D = 4, E = 5, F = 6, G = 7, H = 8, I = 9
  Negative: } = 0, J = 1, K = 2, L = 3, M = 4, N = 5, O = 6, P = 7, Q = 8, R = 9
"""

import os
import sys
from decimal import Decimal

# Sign overpunch mappings for the last digit of a zoned decimal field
POSITIVE_OVERPUNCH = {'{': '0', 'A': '1', 'B': '2', 'C': '3', 'D': '4',
                      'E': '5', 'F': '6', 'G': '7', 'H': '8', 'I': '9'}
NEGATIVE_OVERPUNCH = {'}': '0', 'J': '1', 'K': '2', 'L': '3', 'M': '4',
                      'N': '5', 'O': '6', 'P': '7', 'Q': '8', 'R': '9'}


def decode_zoned_decimal(raw: str, scale: int) -> Decimal:
    """
    Decode a COBOL zoned decimal (PIC S9(n)Vnn) value with sign overpunch
    on the last character.

    Args:
        raw: The raw string from the fixed-width record (e.g., '00150{')
        scale: Number of implied decimal places (e.g., 2 for V99)

    Returns:
        Decimal value with proper sign and scale
    """
    if not raw:
        return Decimal('0')

    last_char = raw[-1]
    leading = raw[:-1]

    if last_char in POSITIVE_OVERPUNCH:
        digit = POSITIVE_OVERPUNCH[last_char]
        sign = 1
    elif last_char in NEGATIVE_OVERPUNCH:
        digit = NEGATIVE_OVERPUNCH[last_char]
        sign = -1
    elif last_char.isdigit():
        digit = last_char
        sign = 1
    else:
        raise ValueError(f"Invalid overpunch character: '{last_char}' in '{raw}'")

    integer_str = leading + digit
    value = Decimal(integer_str)

    if scale > 0:
        value = value / (10 ** scale)

    return value * sign


def parse_record(line: str) -> dict:
    """Parse a single 50-byte disclosure group record."""
    if len(line) < 22:
        raise ValueError(f"Record too short ({len(line)} bytes): '{line}'")

    acct_group_id = line[0:10]      # PIC X(10)
    tran_type_cd = line[10:12]      # PIC X(02)
    tran_cat_cd = line[12:16]       # PIC 9(04)
    int_rate_raw = line[16:22]      # PIC S9(04)V99

    return {
        'account_group_id': acct_group_id.strip(),
        'transaction_type_code': tran_type_cd.strip(),
        'transaction_category_code': int(tran_cat_cd),
        'interest_rate': decode_zoned_decimal(int_rate_raw, 2),
    }


def escape_sql(value: str) -> str:
    """Escape single quotes for SQL string literals."""
    return value.replace("'", "''")


def generate_sql(records: list) -> str:
    """Generate SQL INSERT statements from parsed records."""
    lines = [
        "-- Seed data for disclosure_groups table",
        "-- Source: app/data/ASCII/discgrp.txt (51 records)",
        "-- Generated by scripts/parse_discgrp.py",
        "",
    ]

    for rec in records:
        lines.append(
            f"INSERT INTO disclosure_groups "
            f"(account_group_id, transaction_type_code, transaction_category_code, interest_rate) "
            f"VALUES ("
            f"'{escape_sql(rec['account_group_id'])}', "
            f"'{escape_sql(rec['transaction_type_code'])}', "
            f"{rec['transaction_category_code']}, "
            f"{rec['interest_rate']:.2f}"
            f");"
        )

    return '\n'.join(lines) + '\n'


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)

    input_file = os.path.join(repo_root, 'app', 'data', 'ASCII', 'discgrp.txt')
    output_file = os.path.join(
        repo_root, 'java-migration', 'src', 'main', 'resources',
        'db', 'migration', 'V1.1__seed_disclosure_groups.sql'
    )

    if not os.path.exists(input_file):
        print(f"Error: Input file not found: {input_file}", file=sys.stderr)
        sys.exit(1)

    records = []
    with open(input_file, 'r') as f:
        for line_num, line in enumerate(f, start=1):
            line = line.rstrip('\n').rstrip('\r')
            if not line:
                continue
            try:
                record = parse_record(line)
                records.append(record)
            except (ValueError, IndexError) as e:
                print(f"Warning: Skipping line {line_num}: {e}", file=sys.stderr)

    sql = generate_sql(records)

    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, 'w') as f:
        f.write(sql)

    print(f"Parsed {len(records)} records from {input_file}")
    print(f"Generated SQL: {output_file}")

    # Print summary
    for i, rec in enumerate(records[:3], start=1):
        print(f"  Record {i}: group={rec['account_group_id']}, "
              f"type={rec['transaction_type_code']}, "
              f"cat={rec['transaction_category_code']}, "
              f"rate={rec['interest_rate']}")
    if len(records) > 3:
        print(f"  ... and {len(records) - 3} more records")


if __name__ == '__main__':
    main()
