server:
  port: 8080

spring:
  application:
    name: statement-service

services:
  account:
    base-url: http://account-service:8080
  card:
    base-url: http://card-service:8080
  transaction:
    base-url: http://transaction-service:8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
