-- Bill Payment schema — derived from copybooks CVACT01Y (ACCOUNT-RECORD),
-- CVACT03Y (CARD-XREF-RECORD) and CVTRA05Y (TRAN-RECORD).
-- Portable DDL: runs on IBM DB2 and on H2 (MODE=DB2).

CREATE TABLE ACCOUNT (
    ACCT_ID                BIGINT        NOT NULL,
    ACCT_ACTIVE_STATUS     CHAR(1),
    ACCT_CURR_BAL          DECIMAL(12,2),
    ACCT_CREDIT_LIMIT      DECIMAL(12,2),
    ACCT_CASH_CREDIT_LIMIT DECIMAL(12,2),
    ACCT_OPEN_DATE         VARCHAR(10),
    ACCT_EXPIRAION_DATE    VARCHAR(10),
    ACCT_REISSUE_DATE      VARCHAR(10),
    ACCT_CURR_CYC_CREDIT   DECIMAL(12,2),
    ACCT_CURR_CYC_DEBIT    DECIMAL(12,2),
    ACCT_ADDR_ZIP          VARCHAR(10),
    ACCT_GROUP_ID          VARCHAR(10),
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (ACCT_ID)
);

CREATE TABLE CARD_XREF (
    XREF_CARD_NUM CHAR(16) NOT NULL,
    XREF_CUST_ID  BIGINT,
    XREF_ACCT_ID  BIGINT,
    CONSTRAINT PK_CARD_XREF PRIMARY KEY (XREF_CARD_NUM)
);

-- Secondary access path mirroring the CXACAIX AIX (read by account id).
CREATE INDEX IX_CARD_XREF_ACCT ON CARD_XREF (XREF_ACCT_ID);

CREATE TABLE TRANSACTION (
    TRAN_ID            CHAR(16)      NOT NULL,
    TRAN_TYPE_CD       CHAR(2),
    TRAN_CAT_CD        INTEGER,
    TRAN_SOURCE        VARCHAR(10),
    TRAN_DESC          VARCHAR(100),
    TRAN_AMT           DECIMAL(11,2),
    TRAN_MERCHANT_ID   BIGINT,
    TRAN_MERCHANT_NAME VARCHAR(50),
    TRAN_MERCHANT_CITY VARCHAR(50),
    TRAN_MERCHANT_ZIP  VARCHAR(10),
    TRAN_CARD_NUM      CHAR(16),
    TRAN_ORIG_TS       VARCHAR(26),
    TRAN_PROC_TS       VARCHAR(26),
    CONSTRAINT PK_TRANSACTION PRIMARY KEY (TRAN_ID)
);
